### PR TITLE
Feat/create storage for files

### PR DESCRIPTION
**Pull request by kamilfedio**
I found way to use Mini0 without this strange library (it wasn't updated for last 4 years xD). 
I added instructions in docs with example of use

EDITED
I just used localfile system

### CODE REVIEW

**Comment by Rei-x** [comment]
what about using just a simple disk driver? that stores files in the filesystem

**Comment by kamilfedio** [comment]
@Rei-x sb suggested this and I thought about sth which can be back-upped and more customisable - others microservices

**Comment by Rei-x** [comment]
> @Rei-x sb suggested this and I thought about sth which can be back-upped and more customisable - others microservices

@kamilfedio  tbh, it would be easier for everyone (and especially for me) that for now you would use the simplest solution - aka local filesystem, minio is an overkill for your use-case 😭

**Review by czaja307 — DISMISSED** [review]
LGTM

**Comment by czaja307** [comment]
@Rei-x teraz pytanie jak to załatwić od strony coolify, żeby się zapisywało

**Comment by czaja307** [comment]
> https://coolify.io/docs/knowledge-base/persistent-storage/
> 
> dodaj po prostu wolumen na dane

to wygląda zbyt prosto, żeby było prawdziwe 🧐
dzięki za pomoc

**Review by czaja307 — APPROVED** [review]

**Pull request merged**
